### ISSUE TITLE
MUFFIN class-annot feedback: no such file: /home/ubuntu/null

### ISSUE THREAD

**Issue by dzolier** [RVanDamme/MUFFIN#35]
Hello,

I'm trying to run MUFFIN's class-annot steps and running into some trouble. It seems like I'm not structuring the .csv properly.

My command is as follows:
`nextflow -log /home/ubuntu/MUFFIN_skip_assembly/assembly_skipped.log run RVanDamme/MUFFIN/main.nf --output /home/ubuntu/MUFFIN_skip_assembly/ --ont /home/ubuntu/TFQAB/zip_out/filtlong/filtlong_out.fastq --illumina /home/ubuntu/TFQAB/zip_out/intermediary/*.fastq --bin_classify /home/ubuntu/assembled_bins.csv --bin_assemble /home/ubuntu/assembled_bins.csv --cpus 120 --memory 490g --check_db /home/ubuntu/nextflow-autodownload-databases/checkm/db/ --eggnog_db /home/ubuntu/nextflow-autodownload-databases/eggnogdb_5.0.1 --sourmash_db /home/ubuntu/nextflow-autodownload-databases/sourmash/genbank-k31.lca.json.gz --modular class-annot -profile local,conda`

And my .csv is structured as follows:
```
metawrap_50_10_bin_1,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.1.fa
metawrap_50_10_bin_2,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.2.fa
metawrap_50_10_bin_3,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.3.fa
metawrap_50_10_bin_4,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.4.fa
metawrap_50_10_bin_5,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.5.fa
metawrap_50_10_bin_6,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.6.fa
metawrap_50_10_bin_7,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.7.fa
metawrap_50_10_bin_8,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.8.fa
```

which is giving me the result

```
N E X T F L O W  ~  version 21.10.5
Launching `RVanDamme/MUFFIN` [mad_bhabha] - revision: 939ff8ca71 [master]
[-        ] process > checkm                 -
[-        ] process > sourmash_bins          -
[-        ] process > sourmash_checkm_parser -
[-        ] process > eggnog_bin             -
[-        ] process > parser_bin             -
[-        ] process > readme_output          -

*********Start running MUFFIN*********
[-        ] process > checkm                 -
[-        ] process > sourmash_bins          -
[-        ] process > sourmash_checkm_parser -
[-        ] process > eggnog_bin             -
[-        ] process > parser_bin             -
[-        ] process > readme_output          -

*********Start running MUFFIN*********
MUFFIN is a hybrid assembly and differential binning workflow for metagenomics, transcriptomics and pathway analysis.

If you use MUFFIN for your research pleace cite:

https://www.biorxiv.org/content/10.1101/2020.02.08.939843v1
[-        ] process > checkm                 -
[-        ] process > sourmash_bins          [  0%] 0 of 8
[-        ] process > sourmash_checkm_parser -
[-        ] process > eggnog_bin             -
[-        ] process > parser_bin             -
[-        ] process > readme_output          [  0%] 0 of 1

*********Start running MUFFIN*********
MUFFIN is a hybrid assembly and differential binning workflow for metagenomics, transcriptomics and pathway analysis.

If you use MUFFIN for your research pleace cite:

https://www.biorxiv.org/content/10.1101/2020.02.08.939843v1

or

Van Damme R., Hölzer M., Viehweger A., Müller B., Bongcam-Rudloff E., Brandt C., 2020
"Metagenomics workflow for hybrid assembly, differential coverage binning, transcriptomics and pathway analysis (MUFFIN)",
doi: https://doi.org/10.1101/2020.02.08.939843
**************************************

[metawrap_50_10_bin_1, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.1.fa]
[metawrap_50_10_bin_2, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.2.fa]
[metawrap_50_10_bin_3, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.3.fa]
[metawrap_50_10_bin_4, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.4.fa]
[metawrap_50_10_bin_5, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.5.fa]
[metawrap_50_10_bin_6, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.6.fa]
[metawrap_50_10_bin_7, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.7.fa]
[metawrap_50_10_bin_8, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.8.fa]
No such file: /home/ubuntu/null

 -- Check script '.nextflow/assets/RVanDamme/MUFFIN/main.nf' at line: 571 or see '/home/ubuntu/MUFFIN_skip_assembly/assembly_skipped.log' file for more details
```

For the record, I also tried:
`metawrap_50_10,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.1.fa,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.2.fa,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.3.fa,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.4.fa,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.5.fa,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.6.fa,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.7.fa,/home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.8.fa`

which worked, but:
: the `bin_annotation` folder only shows `bin.2.annotations.tsv` & `bin.2.seed_orthologs.tsv`
: `parser_result` only seems to provide results for `bin.2` as well (`MUFFIN_bin.2_result.html` & `MUFFIN_sample_result.html`)
: `classify' only looks to have results related to `bin.1`

The MUFFIN readme seems to say that each `/n` goes with sample name followed by absolute path of sample, which the former version has. I'm going to try just listing the sample path twice per row and seeing if that works, but in case that doesn't work, I thought you might have some thoughts.

**Comment by dzolier** [comment]
Adding the duplicate absolute path seems to have worked, but a new problem has arisen:

Now, I'm getting a key error from `sourmash_checkm_parser`:
```
[metawrap_50_10_bin_1, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.1.fa]
executor >  local (8)
[f1/4841c4] process > checkm (5)                 [ 62%] 5 of 8, cached: 5
[ac/99d26b] process > sourmash_bins (3)          [100%] 8 of 8, cached: 8 ✔
[31/17d875] process > sourmash_checkm_parser (2) [  0%] 0 of 5
[40/fa5550] process > eggnog_bin (4)             [100%] 8 of 8, cached: 8 ✔
[c1/b09ccc] process > parser_bin (1)             [ 75%] 6 of 8
[63/b9925d] process > readme_output              [100%] 1 of 1, cached: 1 ✔
Error executing process > 'sourmash_checkm_parser (2)'

Caused by:
executor >  local (8)
[f1/4841c4] process > checkm (5)                 [ 62%] 5 of 8, cached: 5
[ac/99d26b] process > sourmash_bins (3)          [100%] 8 of 8, cached: 8 ✔
[31/17d875] process > sourmash_checkm_parser (2) [ 20%] 1 of 5, failed: 1
[40/fa5550] process > eggnog_bin (4)             [100%] 8 of 8, cached: 8 ✔
[c1/b09ccc] process > parser_bin (1)             [ 85%] 6 of 7
[63/b9925d] process > readme_output              [100%] 1 of 1, cached: 1 ✔
Error executing process > 'sourmash_checkm_parser (2)'

Caused by:
  Process `sourmash_checkm_parser (2)` terminated with an error exit status (1)

Command executed:

  grep -v "] INFO: " summary.txt | grep -v "\-\-\-\-\-\-\-" | grep -v "Bin Id" | sed -e 's/^[ \t]*//'|sed 's/[ \t]*$//' |sed -r 's/ +/,/g'|sed '/^$/d' >checkm.csv
  for file in $(ls bin*.txt); do tail -n 1 $file | sed -e 's/.fa//' >>sourmash.csv; done
  checkm_sourmash_parser.py -c checkm.csv -s sourmash.csv

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/ubuntu/.nextflow/assets/RVanDamme/MUFFIN/bin/checkm_sourmash_parser.py", line 93, in <module>
      main()
    File "/home/ubuntu/.nextflow/assets/RVanDamme/MUFFIN/bin/checkm_sourmash_parser.py", line 85, in main
      parse(args)
    File "/home/ubuntu/.nextflow/assets/RVanDamme/MUFFIN/bin/checkm_sourmash_parser.py", line 53, in parse
      dict_checkm_sourmash = sourmash_parser(dict_checkm_sourmash, sourmash)
    File "/home/ubuntu/.nextflow/assets/RVanDamme/MUFFIN/bin/checkm_sourmash_parser.py", line 25, in sourmash_parser
      dict_checkm_sourmash[row[0]].extend( row[1:] )
  KeyError: 'bin.1'

Work dir:
  /home/ubuntu/work/31/17d875cdcccd85bc7c2328d25dbe8b

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

I'm afraid I have no idea what the problem is on this one. I know that Python returns a `KeyError` when the key doesn't exist in a dictionary, but I'm a little confused about where exactly this key doesn't exist.

Any ideas you might have are greatly appreciated.

**Comment by replikation** [comment]
@RVanDamme any idea regarding this?

**Comment by dzolier** [comment]
I have found a few more pieces of information, in case they help.

My checkm.csv file reads as follows:
`bin.2,o__Sphingomonadales,(UID3310),26,569,293,2,561,5,1,0,0,99.64,1.48,12.50`

Whereas my `sourmash.csv` file reads thus:
```
bin.1,found,Bacteria,Firmicutes,Bacilli,Bacillales,Paenibacillaceae,Paenibacillus,,
bin.2,disagree,Bacteria,Proteobacteria,Alphaproteobacteria,Sphingomonadales,Sphingomonadaceae,Sphingopyxis,,
bin.3,found,Bacteria,Bacteroidetes,Chitinophagia,Chitinophagales,Chitinophagaceae,Niastella,Niastella populi,
bin.4,disagree,Bacteria,Proteobacteria,Betaproteobacteria,Burkholderiales,Comamonadaceae,Variovorax,,
bin.5,disagree,Bacteria,Firmicutes,Bacilli,Bacillales,Bacillaceae,Bacillus,,
bin.6,nomatch,,,,,,,,
bin.7,disagree,Bacteria,Firmicutes,Bacilli,Bacillales,Paenibacillaceae,Paenibacillus,,
bin.8,found,Bacteria,Firmicutes,Bacilli,Bacillales,Bacillaceae,Bacillus,Bacillus subtilis,
```

As far as `checkm.nf` outputs go, I see 5 `taxonomy.txt` files and 8 `summary.txt` files lying around:
```
(base) ubuntu@ip-172-31-7-4:~$ find /home/ubuntu/work -iname summary.txt
/home/ubuntu/work/f1/4841c4157cbe44123caa270ba08ffc/summary.txt
/home/ubuntu/work/51/b568c4feaa2a9a5bb42bf7e8d67d7c/summary.txt
/home/ubuntu/work/7b/9010596449084d52a2fe3a04252e14/summary.txt
/home/ubuntu/work/31/17d875cdcccd85bc7c2328d25dbe8b/summary.txt
/home/ubuntu/work/87/76e144c7a4c5db64adf692149f9df5/summary.txt
/home/ubuntu/work/a0/309ad21707099f74d21a95573fde70/summary.txt
/home/ubuntu/work/06/4eac7efcaf8693be5ba4562973f392/summary.txt
/home/ubuntu/work/80/ce5c7c9eef078e6f9efc5f4904abdb/summary.txt
```
and
```
(base) ubuntu@ip-172-31-7-4:~$ find /home/ubuntu/work -iname taxonomy.txt
/home/ubuntu/work/f1/4841c4157cbe44123caa270ba08ffc/taxonomy.txt
/home/ubuntu/work/7b/9010596449084d52a2fe3a04252e14/taxonomy.txt
/home/ubuntu/work/87/76e144c7a4c5db64adf692149f9df5/taxonomy.txt
/home/ubuntu/work/06/4eac7efcaf8693be5ba4562973f392/taxonomy.txt
/home/ubuntu/work/80/ce5c7c9eef078e6f9efc5f4904abdb/taxonomy.txt
```
 I'm not sure how helpful all this is, but I am not exactly having an easy time understanding the issue so I'm grateful for any insights.

**Comment by dzolier** [comment]
I found a way to do it.
My guess had something to do with the program reading the file a certain way, but I used two alterations to the script to get it past the part I've been having trouble with.

So first, I gave them all the same first column name, so all of them are in `metawrap_50_10` instead of in `metawrap_50_10_bin_*` like prior. And second, is the thing in the previous comment where I added a duplicate path. My current assembled_bins.csv looks like this:
```
metawrap_50_10,/ABS_PATH_TO/metawrap_50_10_bins/bin.1.fa,/ABS_PATH_TO/metawrap_50_10_bins/bin.1.fa
metawrap_50_10,/ABS_PATH_TO/metawrap_50_10_bins/bin.2.fa,/ABS_PATH_TO/metawrap_50_10_bins/bin.2.fa

```
... and so on, which takes me through eggnog but now it's `pankegg_bin.py` that isn't working; it's outputted a single `bin_6.result` file instead of the eight I was expecting, and the `.result` files are filled with "unknow by KEGG DB" entries.


Unfortunately, there were no errors this time. I have a guess it has something to do with the fact that I cut it off after it seemed to have stalled either in or before the `parser_bin` step in the penultimate run. The final `-resume` took less than five minutes.

cut it off at the bottom of this part:
```

Van Damme R., Hölzer M., Viehweger A., Müller B., Bongcam-Rudloff E., Brandt C.,executor >  local (3)
[ce/5afe22] process > checkm (1)                 [100%] 1 of 1, cached: 1 ✔
[1f/bd615b] process > sourmash_bins (4)          [100%] 8 of 8, cached: 8 ✔
[b8/9b19b1] process > sourmash_checkm_parser (1) [100%] 1 of 1 ✔
[81/0064e9] process > eggnog_bin (6)             [100%] 8 of 8, cached: 7 ✔
[5f/10b431] process > parser_bin (1)             [  0%] 0 of 1
[ce/7fc4a1] process > readme_output              [100%] 1 of 1, cached: 1 ✔
executor >  local (3)
[ce/5afe22] process > checkm (1)                 [100%] 1 of 1, cached: 1 ✔
[1f/bd615b] process > sourmash_bins (4)          [100%] 8 of 8, cached: 8 ✔
[b8/9b19b1] process > sourmash_checkm_parser (1) [100%] 1 of 1 ✔
[81/0064e9] process > eggnog_bin (6)             [100%] 8 of 8, cached: 7 ✔
[5f/10b431] process > parser_bin (1)             [  0%] 0 of 1
[ce/7fc4a1] process > readme_output              [100%] 1 of 1, cached: 1 ✔
[metawrap_50_10, [/home/ubuntu/work/fc/3964aefc155eb93a112e7996e507ea/bin.6.annotations.tsv, /home/ubuntu/work/dd/97c8b92b5405b9e3a1928282f7efbe/bin.3.annotations.tsv, /home/ubuntu/work/9b/bfa547a61fff7c6cfd340d5727316f/bin.2.annotations.tsv, /home/ubuntu/work/43/0d537f672418326d28bd328d6c1f1c/bin.4.annotations.tsv, /home/ubuntu/work/1f/65f376470cb6df587bd859f25ce0c1/bin.5.annotations.tsv, /home/ubuntu/work/94/cae3df3ddc54e14c445b88720e8832/bin.8.annotations.tsv, /home/ubuntu/work/5b/d18d10ea3964c3ab5bd134894840ca/bin.1.annotations.tsv, /home/ubuntu/work/81/0064e99019e2e49b72674a9f1726e5/bin.7.annotations.tsv]]
```

And resumed afterward:
```
(base) ubuntu@ip-172-31-13-21:~$ nextflow -log /home/ubuntu/MUFFIN_skip_assembly/assembly_skipped_resume_001.log run RVanDamme/MUFFIN/main.nf --output /home/ubuntu/MUFFIN_skip_assembly/ --ont /home/ubuntu/TFQAB/zip_out/filtlong/filtlong_out.fastq --illumina /home/ubuntu/TFQAB/zip_out/intermediary/*.fastq --bin_classify /home/ubuntu/assembled_bins.csv --bin_assemble /home/ubuntu/assembled_bins.csv --cpus 120 --memory 490g --check_db /home/ubuntu/nextflow-autodownload-databases/checkm/db/ --eggnog_db /home/ubuntu/nextflow-autodownload-databases/eggnogdb_5.0.1 --sourmash_db /home/ubuntu/nextflow-autodownload-databases/sourmash/genbank-k31.lca.json.gz --modular class-annot -profile local,conda -resume
N E X T F L O W  ~  version 21.10.5
Launching `RVanDamme/MUFFIN` [gloomy_lichterman] - revision: 939ff8ca71 [master]
[-        ] process > checkm                 -
[-        ] process > sourmash_bins          -
[-        ] process > sourmash_checkm_parser -
[-        ] process > eggnog_bin             -
[-        ] process > parser_bin             -
[-        ] process > readme_output          -

*********Start running MUFFIN*********
MUFFIN is a hybrid assembly and differential binning workflow for metagenomics, transcriptomics and pathway analysis.

If you use MUFFIN for your research pleace cite:
[-        ] process > checkm                 -
[-        ] process > sourmash_bins          -
[-        ] process > sourmash_checkm_parser -
[-        ] process > eggnog_bin             -
[-        ] process > parser_bin             -
[-        ] process > readme_output          -

*********Start running MUFFIN*********
MUFFIN is a hybrid assembly and differential binning workflow for metagenomics, transcriptomics and pathway analysis.

If you use MUFFIN for your research pleace cite:

https://www.biorxiv.org/content/10.1101/2020.02.08.939843v1

or

Van Damme R., Hölzer M., Viehweger A., Müller B., Bongcam-Rudloff E., Brandt C., 2020
[ce/5afe22] process > checkm (1)                 [100%] 1 of 1, cached: 1 ✔
[64/408ca5] process > sourmash_bins (3)          [100%] 8 of 8, cached: 8 ✔
[b8/9b19b1] process > sourmash_checkm_parser (1) [100%] 1 of 1, cached: 1 ✔
[43/0d537f] process > eggnog_bin (5)             [100%] 8 of 8, cached: 8 ✔
[5f/10b431] process > parser_bin (1)             [100%] 1 of 1, cached: 1 ✔
[ce/7fc4a1] process > readme_output              [100%] 1 of 1, cached: 1 ✔

*********Start running MUFFIN*********
MUFFIN is a hybrid assembly and differential binning workflow for metagenomics, transcriptomics and pathway analysis.

If you use MUFFIN for your research pleace cite:

https://www.biorxiv.org/content/10.1101/2020.02.08.939843v1

or

Van Damme R., Hölzer M., Viehweger A., Müller B., Bongcam-Rudloff E., Brandt C., 2020
"Metagenomics workflow for hybrid assembly, differential coverage binning, transcriptomics and pathway analysis (MUFFIN)",
doi: https://doi.org/10.1101/2020.02.08.939843
**************************************

[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.1.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin[ce/5afe22] process > checkm (1)                 [100%] 1 of 1, cached: 1 ✔
[64/408ca5] process > sourmash_bins (3)          [100%] 8 of 8, cached: 8 ✔
[b8/9b19b1] process > sourmash_checkm_parser (1) [100%] 1 of 1, cached: 1 ✔
[43/0d537f] process > eggnog_bin (5)             [100%] 8 of 8, cached: 8 ✔
[5f/10b431] process > parser_bin (1)             [100%] 1 of 1, cached: 1 ✔
[ce/7fc4a1] process > readme_output              [100%] 1 of 1, cached: 1 ✔

*********Start running MUFFIN*********
MUFFIN is a hybrid assembly and differential binning workflow for metagenomics, transcriptomics and pathway analysis.

If you use MUFFIN for your research pleace cite:

https://www.biorxiv.org/content/10.1101/2020.02.08.939843v1

or

Van Damme R., Hölzer M., Viehweger A., Müller B., Bongcam-Rudloff E., Brandt C., 2020
"Metagenomics workflow for hybrid assembly, differential coverage binning, transcriptomics and pathway analysis (MUFFIN)",
doi: https://doi.org/10.1101/2020.02.08.939843
**************************************

[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.1.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.2.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.3.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.4.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.1.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.5.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.6.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.7.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.8.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.2.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.3.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.4.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.5.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.6.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.7.fa]
[metawrap_50_10, /home/ubuntu/TFQAB/zip_out/metaWRAP_out/metawrap_50_10_bins/bin.8.fa]
[metawrap_50_10, [/home/ubuntu/work/dd/97c8b92b5405b9e3a1928282f7efbe/bin.3.annotations.tsv, /home/ubuntu/work/9b/bfa547a61fff7c6cfd340d5727316f/bin.2.annotations.tsv, /home/ubuntu/work/1f/65f376470cb6df587bd859f25ce0c1/bin.5.annotations.tsv, /home/ubuntu/work/94/cae3df3ddc54e14c445b88720e8832/bin.8.annotations.tsv, /home/ubuntu/work/fc/3964aefc155eb93a112e7996e507ea/bin.6.annotations.tsv, /home/ubuntu/work/81/0064e99019e2e49b72674a9f1726e5/bin.7.annotations.tsv, /home/ubuntu/work/43/0d537f672418326d28bd328d6c1f1c/bin.4.annotations.tsv, /home/ubuntu/work/5b/d18d10ea3964c3ab5bd134894840ca/bin.1.annotations.tsv]]

Done! Results are stored here --> /home/ubuntu/MUFFIN_skip_assembly/
 The Readme file in /home/ubuntu/MUFFIN_skip_assembly/ describe the structure of the results directories.
```

But as I said, there's just `bin.6_result.html` and the `sample` result in the `parser_result` folder, and I'm not sure why.
